# This will be replaced with trigger from main branch
trigger: none

resources:
  repositories:
    # This is the repository where ADO pipeline templates and common bash functions are stored
    - repository: utils
      type: github
      name: 'launchbynttdata/lcaf-component-provider_az-pipeline_azdo'
      ref: feature/1456
      endpoint: 'launchbynttdata-github-token'

variables:
  utils_ref: $[ resources.repositories.utils.ref ]
  utils_name: $[ resources.repositories.utils.name ]
  utils_id: $[ resources.repositories.utils.id ]
  utils_type: $[ resources.repositories.utils.type ]
  utils_url: $[ resources.repositories.utils.url ]
  utils_version: $[ resources.repositories.utils.version ]
  service_connection_dev: "ado-sp"
  service_connection_qa: "ado-sp"
  service_connection_prod: "ado-sp"
  service_connection_sandbox: "ado-sp"

parameters:
  - name: serviceConnection
    type: string
    default: 'ado-sp'

pool: 'container-pool'

stages:
  - template: ./templates/stages/terragrunt.yaml
    parameters:
      deployEnvironments:
        - environment: sandbox
          region: eastus
          environmentNumber: "000"
          azureEnvironment: tg-vnet-sandbox-eastus-000
          serviceConnection: $(service_connection_sandbox)
        # - environment: sandbox
        #   region: eastus
        #   environmentNumber: "001"
        #   azureEnvironment: tg-vnet-sandbox-eastus-001
        # - environment: qa
        #   region: eastus
        #   environmentNumber: "000"
        #   azureEnvironment: tg-vnet-qa-eastus-000
        #   dependsOn:
        #     - sandbox_eastus_000_deploy
        #     - sandbox_eastus_001_deploy
        # - environment: uat
        #   region: eastus
        #   environmentNumber: "000"
        #   azureEnvironment: tg-vnet-uat-eastus-000
        #   dependsOn:
        #     - qa_eastus_000_deploy
        # - environment: prod
        #   region: eastus
        #   environmentNumber: "000"
        #   azureEnvironment: tg-vnet-prod-eastus-000
        #   dependsOn:
        #     - uat_eastus_000_deploy
      subscription: ${{ parameters.serviceConnection }}
      pool: 'container-pool'
      repoCheckoutSteps:
        - checkout: self
          path: main
        - checkout: utils
          path: utils